### ISSUE TITLE
Colors not working for realistic season addon

### ISSUE THREAD

**Issue by TomcatHD** [hyperdefined/TimeBar#63] opened 2024-08-04 18:43 UTC
colors:
  SPRING: "PINK"
  SUMMER: "YELLOW"
  FALL: "RED"
  WINTER: "BLUE"
  
  none of those colors are working for the SEASON placeholder.

**Comment by hyperdefined** [comment] 2024-08-04 23:06
It works for me fine on a fresh new server. What is your RealisticSeasons version? Can you show me your `plugins/TimeBar/realisticseasons.yml` config?

Not sure if it's a copy & paste issue, but your colors section should be indented like this:
```yaml
colors:
  SPRING: "PINK"
  SUMMER: "YELLOW"
  FALL: "RED"
  WINTER: "BLUE"
```

**Comment by TomcatHD** [comment] 2024-08-06 00:08
`# Use 24hr format for times.
use-24h-format: true

# Set the text of the TimeBar.
# {TIME} - The current world time, 7:20 am, etc.
# {TIME-WORD} - The time to display. Dawn, afternoon, etc.
# {DAYCOUNT} - How many total days in game have passed.
# {SEASON} - The current season.
# {DATE} - The current date.
# {DAY} - The day of week.
# {MONTH} - The month.
# {DAYPERCENT} - Percentage of day completion.
timebar-title: "<green>{TIME}</green> - <gold>{TIME-WORD}</gold> <gray>({DATE}) {DAY}</gray> - <red>{SEASON}</red>"

# Change the default formatting for dates.
# See: https://www.digitalocean.com/community/tutorials/java-simpledateformat-java-date-format
# Example: "dd/MM/yyyy"
date-format: "dd/MM"

# Want to change the wording of the time of days?
times:
  dawn: "Sonnenaufgang"
  morning: "Morgen"
  noon: "Mittag"
  afternoon: "Nachmittag"
  sunset: "Sonnenuntergang"
  night: "Nacht"
  midnight: "Mitternacht"

# Set the color per season for the TimeBar.
# The valid options are: blue, green, pink, purple, red, white, and yellow.
colors:
  SPRING: "PINK"
  SUMMER: "YELLOW"
  FALL: "RED"
  WINTER: "BLUE"

# Set each "time of day" for each month.
# When the time hits one of these, it will turn that "time of day."
# Example: January at 7:45 AM. It will be dawn.
# You can also set each title for each month, just add the title section like below and remove the #
month:
  january:
    name: "Januar"
    dawn: "06:00"
    morning: "08:30"
    noon: "12:00"
    afternoon: "15:00"
    sunset: "16:30"
    night: "18:30"
    midnight: "00:00"
    #title: "This title will show in January only."
  february:
    name: "Februar"
    dawn: "05:25"
    morning: "08:00"
    noon: "12:00"
    afternoon: "15:35"
    sunset: "17:00"
    night: "18:50"
    midnight: "00:00"
    #title: "This title will show in February only."
  march:
    name: "März"
    dawn: "05:00"
    morning: "07:30"
    noon: "12:00"
    afternoon: "16:00"
    sunset: "17:45"
    night: "19:15"
    midnight: "00:00"
  april:
    name: "April"
    dawn: "04:30"
    morning: "07:00"
    noon: "12:00"
    afternoon: "16:30"
    sunset: "18:20"
    night: "19:45"
    midnight: "00:00"
  may:
    name: "Mai"
    dawn: "04:00"
    morning: "06:30"
    noon: "12:00"
    afternoon: "17:00"
    sunset: "18:55"
    night: "20:05"
    midnight: "00:00"
  june:
    name: "Juni"
    dawn: "03:35"
    morning: "06:00"
    noon: "12:00"
    afternoon: "17:30"
    sunset: "19:30"
    night: "20:30"
    midnight: "00:00"
  july:
    name: "Juli"
    dawn: "03:10"
    morning: "05:30"
    noon: "12:00"
    afternoon: "18:00"
    sunset: "20:00"
    night: "21:00"
    midnight: "00:00"
  august:
    name: "August"
    dawn: "03:35"
    morning: "06:00"
    noon: "12:00"
    afternoon: "17:30"
    sunset: "19:30"
    night: "20:30"
    midnight: "00:00"
  september:
    name: "September"
    dawn: "04:00"
    morning: "06:30"
    noon: "12:00"
    afternoon: "17:00"
    sunset: "18:55"
    night: "20:05"
    midnight: "00:00"
  october:
    name: "Oktober"
    dawn: "04:30"
    morning: "07:00"
    noon: "12:00"
    afternoon: "16:30"
    sunset: "18:20"
    night: "19:45"
    midnight: "00:00"
  november:
    name: "November"
    dawn: "05:00"
    morning: "07:30"
    noon: "12:00"
    afternoon: "16:00"
    sunset: "17:45"
    night: "19:15"
    midnight: "00:00"
  december:
    name: "Dezember"
    dawn: "05:30"
    morning: "08:00"
    noon: "12:00"
    afternoon: "15:35"
    sunset: "17:00"
    night: "18:50"
    midnight: "00:00"

# No touch please :)
config-version: 4`

this is my config, im using the latest version of realistic seasons

**Comment by TomcatHD** [comment] 2024-08-06 00:14
this is my realisticseasons.yml  file https://pastebin.com/hXs2Wuxg
im using the latest version on 1.2.1

**Comment by hyperdefined** [comment] 2024-08-06 05:30
![Medal_2024-08-06_01-29-56](https://github.com/user-attachments/assets/65f12c26-a182-4d66-8f4e-53ec49f37929)
![Medal_2024-08-06_01-30-07](https://github.com/user-attachments/assets/8bb0c9bf-b6cc-4621-9c02-f06778860038)

Your config is working for me perfectly fine. What color does the TimeBar appear as? Try to change it via `/plugins/TimeBar/config.yml` instead, see if that changes there.

**Comment by TomcatHD** [comment] 2024-08-09 01:23
the color changes when using the main config, but nothing changes when using the realisticseasons.yml color section, im on version 1.20.1 btw, not 1.2.1 sorry

**Comment by hyperdefined** [comment] 2024-08-09 01:26
Is it only the color not working? The title is loading fine?

**Comment by TomcatHD** [comment] 2024-08-09 12:59
yep, only the color

**Comment by hyperdefined** [comment] 2024-08-12 01:14
I will have to make a test version for you to use. I would suggest joining the help Discord to chat better: https://discord.gg/rJuQXVcJz8

**Comment by hyperdefined** [comment] 2024-08-25 21:33
Closed as reporter never responded in the Discord, can't reproduce error on my end.

**Closed by hyperdefined** 2024-08-25 21:33 UTC
