### ISSUE TITLE
Console error TimeBar 1.4.1 - java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by tantrum90** [hyperdefined/TimeBar#60] opened 2024-06-24 22:29 UTC
on the latest timebar 1.4.1 version there is console error constantly spamming.
https://paste.gg/p/anonymous/8e9b18ccb08f4660b7d158e11f476935

version
24.06 22:03:17 [Server] INFO This server is running Paper version 1.20.6-147-ver/1.20.6@e41d44f (2024-06-17T19:24:35Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

**Comment by hyperdefined** [comment] 2024-06-25 00:21
Hmm something is cutting off your console. Can you possibly copy and paste it from your servers log file instead?

**Comment by tantrum90** [comment] 2024-06-25 00:30
This is the error from logs:

https://paste.gg/p/anonymous/8296fd0764dc41919dc86cb40516f2b2

This started to happen, after I added the new placeholder in the config
timebar-title: "Ден {DAYCOUNT} - {TIME} (%timebar_day_percent% од денот е поминат)"

**Comment by hyperdefined** [comment] 2024-06-25 00:40
Something is not passing the player instance to the placeholder, causing it to break. Not sure why that is the case. I can add check so this doesn't get spammed in your console.

Also, you don't have to use the placeholder in the title, you can use `{DAYPERCENT}`. The placeholder is for other plugins to display.

**Comment by hyperdefined** [comment] 2024-06-25 00:46
[timebar-1.4.1-null-debug.zip](https://github.com/user-attachments/files/15962928/timebar-1.4.1-null-debug.zip)

I made a test version here, can you possibly test this to see if the issue is fixed? The .jar is located in the zip file.

I can't see this issue on my end, would like to see if it's fixed on yours with this test version.

**Closed** 2024-06-25 01:14 UTC
Labels: bug

**Comment by hyperdefined** [comment] 2024-06-25 01:16
Issue has been fixed, update to 1.4.2
